### ISSUE TITLE
No Pools, no errors

### ISSUE THREAD

**Issue by JBaczuk** [bonesoul/CoiniumServ#1031]
I'm able to compile and run Coinium on Ubuntu Server 16.04 using:

`sudo mono build/bin/Debug/CoiniumServ.exe`

but no matter what changes I make to the pool config files, it doesn't add a pool or change the output of the above command (unless I delete the `default.json`) then it throws an error.

How can I debug the RPC connection to the bitcoind daemon to make sure it is working?

**Comment by xborow** [comment]
hi,

after your advice, i still had a problem to compile it on kali linux due to lack of some packages, so i brought up ubuntu 18 on another machine...long short sotry, after playing had compied debug version on the both kali and ubuntu, but on kali the pool did not work, had no pool no errors, but no message about stratum, nothing about webfronted, no messages about mpos/msql&redis), so i knew something is not working,  even any changes I made in config it was not reflected while running mono coinium.., so tried to pack complied version from ubuntu and tested it on kali, then it was all working except mpos, still some issues..

what i did with compiled version from ubuntu.. while setting all things up, in pool i did copy example.default.json to default.json, and did copy bitcoin.example.json to pool.json, did all modifications, and then finally i started the servevr mono coiniumserv.exe, imidiatelly all was comming up, messages about stratum, webfronted, mpos and so on.., now i can do any modifications to pool.json and it will reflect all changes

hope it helps somehow ;)

**Comment by mynamedaike** [comment]
I encountered the same problem in windows. How can I fix it? Thanks in advance.

**Comment by xborow** [comment]
might be wrong, but it could be beacuse of 2 things, issue while compiling or setup issue, i had this issue when it was compiled on kali, but compiled versin from ubuntu works, 2ndly, i was using different way of setting pool, working way: cp default.example.json to default.json, then cp bitcoin.example.json to pool.json, then all modifications done only in pool.json and all starting as expected

**Comment by JBaczuk** [comment]
It seems that for me that circumstance occurs when either the connection details (to the daemon RPC) are incorrect, or the `enable: true` has not been set at the top of the `pool.json` file.
