### ISSUE TITLE
Trying to Mine XVG (Verge) and getting message Wallet is Locked Cannot Sign 

### ISSUE THREAD

**Issue by Virtuworks** [bonesoul/CoiniumServ#829]
![image](https://user-images.githubusercontent.com/12708326/28492141-496e3270-6ecb-11e7-891a-7a31b7c87da4.png)

![image](https://user-images.githubusercontent.com/12708326/28492144-5430874e-6ecb-11e7-9059-dca32537952f.png)

Any Ideas?

https://github.com/vergecurrency/VERGE

**Comment by pfeiflelukas** [comment]
@Virtuworks I was experimenting with verge, and i added some more nodes because verge has a terrible connection to its own network. I then also got a new address from its daemon then re-indexed the blockchain. Didn't get that issue again but didn't receive a payment from mining it, probably from coiniumserv error

**Comment by senselt** [comment]
I experienced the same problem outside of coiniumserv. I'd say it's probably more likely that it's an issue with the wallet.

**Comment by bonesoul** [comment]
Closing it as it seems related to coin itself.
