### ISSUE TITLE
SkunkHash-Raptor Algorithm for Signatum

### ISSUE THREAD

**Issue by mythrill** [bonesoul/CoiniumServ#844]
I have attempted to add [GostStreebog512](https://signatum.io/signatum_whitepaper.pdf) into [HashLib](https://hashlib.codeplex.com/)  by integrating [OpenGost](https://github.com/sergezhigunov/OpenGost) 

```
using OpenGost.Security.Cryptography;

namespace HashLib.Crypto
{
    internal class Gost512 : BlockHash, ICryptoNotBuildIn
    {
        private byte[] m_data = new byte[512];

        public Gost512()
            : base(128, 128)
        {
            Initialize();
        }

        protected override void TransformBlock(byte[] a_data, int a_index)
        {
            var x = Streebog512.Create();
            m_data = x.ComputeHash(a_data, a_index, a_data.Length - a_index);
        }

        protected override byte[] GetResult()
        {
            return m_data;
        }

        protected override void Finish()
        {
            TransformBytes(m_data);
        }

        public override void Initialize()
        {
            m_data.Clear();

            base.Initialize();
        }
    };
}
```

added skunk as a new algorithm and then configured signatum as a new coin and pool successfully

```
_hashers = new List<IHash>
{
 
	HashFactory.Crypto.SHA3.CreateSkein512(),
	HashFactory.Crypto.SHA3.CreateCubeHash512(),
	HashFactory.Crypto.SHA3.CreateFugue512(),
	HashFactory.Crypto.CreateGostStreebog512()

};
```

I am trying to do this as I can see how HashLib is used inside CoiniumServ - or would there be another way to add GostStreebog512 - I have successfully rebuilt OpenGost for the .net framework as opposed to core, and added it to HashLib, so the calls are available but I'm unsure how to test it.

the CoiniumServ code above does not seem to work - If i just try using CreateSkein512() it seems to mine [signatum](https://signatum.io/) ok and find shares successfully - but there is no pool hashrate calculated and Share.cs wouldn't be able to hash the header anyway so it's only partial - I haven't confirmed if the OpenGost is working correctly or if this code can actually do the skunk hash - is there some manual way to test the generated hash?

thanks for CoiniumServ

**Comment by Thomasmcdaniel9** [comment]
Hey would any of you know how to add mining directly into the exchange also adding rig name and worker to pool


Sent from my Samsung Galaxy , an AT&T LTE smartphone
-------- Original message --------From: mythrill <notifications@github.com> Date: 9/12/17  2:31 PM  (GMT-06:00) To: bonesoul/CoiniumServ <CoiniumServ@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [bonesoul/CoiniumServ] SkunkHash-Raptor Algorithm for Signatum (#844) 
I have attempted to add GostStreebog512 into HashLib  by integrating OpenGost
using OpenGost.Security.Cryptography;

namespace HashLib.Crypto
{
    internal class Gost512 : BlockHash, ICryptoNotBuildIn
    {
        private byte[] m_data = new byte[512];

        public Gost512()
            : base(128, 128)
        {
            Initialize();
        }

        protected override void TransformBlock(byte[] a_data, int a_index)
        {
            var x = Streebog512.Create();
            m_data = x.ComputeHash(a_data, a_index, a_data.Length - a_index);
        }

        protected override byte[] GetResult()
        {
            return m_data;
        }

        protected override void Finish()
        {
            TransformBytes(m_data);
        }

        public override void Initialize()
        {
            m_data.Clear();

            base.Initialize();
        }
    };
}

added skunk as a new algorithm and then configured signatum as a new coin and pool successfully
_hashers = new List<IHash>
{
 
	HashFactory.Crypto.SHA3.CreateSkein512(),
	HashFactory.Crypto.SHA3.CreateCubeHash512(),
	HashFactory.Crypto.SHA3.CreateFugue512(),
	HashFactory.Crypto.CreateGostStreebog512()

};

I am trying to do this as I can see how HashLib is used inside CoiniumServ - or would there be another way to add GostStreebog512 - I have successfully rebuilt OpenGost for the .net framework as opposed to core, and added it to HashLib, so the calls are available but I'm unsure how to test it.
the CoiniumServ code above does not seem to work - If i just try using CreateSkein512() it seems to mine signatum ok and find shares successfully - but there is no pool hashrate calculated and Share.cs wouldn't be able to hash the header anyway so it's only partial - I haven't confirmed if the OpenGost is working correctly or if this code can actually do the skunk hash - is there some manual way to test the generated hash?
thanks for CoiniumServ

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bonesoul/CoiniumServ","title":"bonesoul/CoiniumServ","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bonesoul/CoiniumServ"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"SkunkHash-Raptor Algorithm for Signatum (#844)"}],"action":{"name":"View Issue","url":"https://github.com/bonesoul/CoiniumServ/issues/844"}}}

**Comment by mythrill** [comment]
@Thomasmcdaniel9 please start your own "issue" for different questions

**Comment by Thomasmcdaniel9** [comment]
sorry it just came via email thought i would give it shot . thanks

**Comment by mythrill** [comment]
@Thomasmcdaniel9 go to https://github.com/bonesoul/CoiniumServ/issues and click the big green New Issue button dude. :)

**Comment by mythrill** [comment]
I stopped working on it - this won't be needed now the POW phase has finished.
